name: "Blog idea"
description: "글감/초안/연재 아이디어"
title: "[idea] "
labels: ["idea"]
body:
  - type: textarea
    id: why
    attributes:
      label: "왜 이 글을 쓰나? (한 줄)"
      placeholder: "예) 오늘 삽질한 원인/해결을 기록해두면 다음에 30분을 아낀다"
    validations:
      required: true

  - type: textarea
    id: tl;dr
    attributes:
      label: "TL;DR (결론)"
      placeholder: "예) Jekyll 빌드 에러는 X 설정 때문이었고 Y로 해결했다"
    validations:
      required: true

  - type: textarea
    id: outline
    attributes:
      label: "아웃라인"
      placeholder: "- 문제 상황\n- 원인\n- 해결\n- 체크리스트"
    validations:
      required: false

  - type: textarea
    id: references
    attributes:
      label: "참고 링크/자료"
      placeholder: "링크 모음"
    validations:
      required: false
