name: "Site bug"
description: "블로그 렌더링/레이아웃/링크 오류"
title: "[bug] "
labels: ["bug"]
body:
  - type: input
    id: url
    attributes:
      label: "문제 URL"
      placeholder: "https://saab-josu.github.io/..."
    validations:
      required: true

  - type: textarea
    id: what
    attributes:
      label: "무엇이 문제인가"
      placeholder: "예) 링크 404 / 레이아웃 깨짐 / 코드블록 줄바꿈 이상"
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: "기대 동작"
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: "추가 맥락"
      placeholder: "브라우저/스크린샷/재현방법 등"
    validations:
      required: false
